bbasung1/deeptalk-backend

oauth.js, package.json, yarn.lock
=> Feature oauth kakao

profile.js
=> [FEAT]profile.js

general.js, talk.js
=> [FEAT]talk.js

talk.js, think.js
=> [FEAT]think.js

talk.js
=> [Refactor]talk.js

think.js
=> [Refactor]think.js

profile.js
=> id_check add

deeptalk.js, package.json, yarn.lock
=> Feature-oauth_apple

general.js, search.js, talk.js
=> [FEAT]search.js

profile.js
=> set-theme add

oauth.js
=> [FEAT]oauth.js

oauth.js
=> Feature-oauth_signup

profile.js
mute & block add  in profile.js
=> mute & block add

profile.js
in profile.js
/profile/nickname
/profile/nickname/register
code update
=> nick name register and get  code update

profile.js
recovery
* setting theme  -   add
=> profile.js

oauth.js, package.json, yarn.lock
=> Feature-mail_check

comment.js
1. Load comments
- Sort by newest or popularity
2. Increase or decrease the number of likes
3. Increase or decrease the number of quotes
4. Increase or decrease the number of bookmarks
=> Fetching comments and 6 related APIs

admin.js, deeptalk.js, oauth.js
=> Feature-admin

general.js, oauth.js, search.js, useractivity.js
=> Feature-jwt

general.js, useractivity.js
=> [FIX]useractivity.js

oauth.js, profile.js
add check duplicate mail feature
=> Feature-profile_mail

profile.js
=> Feature-profile_block

general.js, profile.js, profile/block.js, profile/mute.js
=> [REFACTOR]profile.js

deeptalk.js, like.js
=> [FEAT]like.js
